services:
  - type: web
    name: my-node-docker-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://USERNAME:PASSWORD@cluster.mongodb.net/mydb
      - key: AUTH_TOKEN
        value: super_secret_token
